/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.Abstract.User;
import Business.Users.Customer;
import Business.Users.Supplier;
import java.awt.CardLayout;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author AEDSpring2019
 */
public class LoginScreen extends javax.swing.JPanel {

    /**
     * Creates new form LoginScreen
     */
    List<User> list;
    JPanel panelRight;
    public LoginScreen(JPanel panelRight, List<User> list) {
        initComponents();
        this.list = list;
        this.panelRight = panelRight;
        if(!list.isEmpty()){
            initialize();
            //comboUser.removeAllItems();
            comboUser.setEnabled(true);
            txtPword.setEnabled(true);
            btnSubmit.setEnabled(true);
        }
        else{
            comboUser.removeAllItems();
            comboUser.setEnabled(false);
            txtPword.setEnabled(false);
            btnSubmit.setEnabled(false);
            //String role=list.toString();
            txtTitle.setText("User Login Screen");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPword = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        comboUser = new javax.swing.JComboBox<>();
        txtTitle = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 204));

        txtPword.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        btnSubmit.setBackground(new java.awt.Color(255, 204, 204));
        btnSubmit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSubmit.setText("Login");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        comboUser.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        comboUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtTitle.setText("User Login Screen");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(388, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSubmit)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtPword, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(comboUser, 0, 166, Short.MAX_VALUE))
                    .addComponent(txtTitle))
                .addContainerGap(346, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(txtTitle)
                .addGap(54, 54, 54)
                .addComponent(comboUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(txtPword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(btnSubmit)
                .addContainerGap(321, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        String pWord= txtPword.getText();
        if(pWord==null || "".equals(pWord)){
            JOptionPane.showMessageDialog(null, "Enter password!");
            return;
        }
        int selectedIndex=comboUser.getSelectedIndex();
        System.out.println("selected index-"  +selectedIndex);
        //String userName = comboUser.getSelectedItem().toString();
        User user=list.get(selectedIndex);
        //Class<? extends List> role = list.getClass();
         int flag=0;
        for(User u: list){
            System.out.println(u.getUserName()+" username "+user);
            System.out.println(u.getPassword()+" pasword "+pWord);
            if(u.verify(pWord) && u.equals(user))
            {
                user=u;
                flag=1;
                SuccessScreen ss = new SuccessScreen(user);
                CardLayout layout = (CardLayout)panelRight.getLayout();
                panelRight.add(ss);
                layout.next(panelRight);
                break;
            }     
           
            }
        if(flag==0){
        JOptionPane.showMessageDialog(null, "Wrong details!");}
        
        
    }//GEN-LAST:event_btnSubmitActionPerformed

    
    private void initialize(){
        //text should either be "Supplier Login Screen" OR "Customer Login Screen"
        //Based on the selection
        
           
        String role= list.get(0).getRole();
        if(role.equals("SUPPLIER")) role="Supplier";
        else role="Customer";
        txtTitle.setText(role+" Login Screen");
        comboUser.removeAllItems();
        //only customer or suppliers should be listed based on the selection
        if(!list.isEmpty()){
        for(User u: list){
        comboUser.addItem(u);
        }
        }
       
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<Object> comboUser;
    private javax.swing.JTextField txtPword;
    private javax.swing.JLabel txtTitle;
    // End of variables declaration//GEN-END:variables
}
